name: Build postgres docker
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Docker version'
        required: true
        default: 'latest'
      type:
        description: 'Docker type'
        required: true
        default: 'postgres'
        type: choice
        options:
          - pgvector
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ github.event.inputs.type }}
          file: ./${{ github.event.inputs.type }}/Dockerfile
          push: true
          tags: clownfishx/pgvector-${{ github.event.inputs.type }}:${{ github.event.inputs.version }}
